export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TRAINER = 'TRAINER',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  STUDENT = 'STUDENT',
  APPLICANT = 'APPLICANT',
  VISITOR = 'VISITOR'
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WAITLISTED = 'WAITLISTED'
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  LEAVE = 'LEAVE'
}

export enum ForceType {
  ARMY = 'ARMY',
  NAVY = 'NAVY',
  AIR_FORCE = 'AIR_FORCE',
  POLICE = 'POLICE',
  RPF = 'RPF',
  CAPF = 'CAPF',
  SSC_GD = 'SSC_GD',
  OTHER = 'OTHER'
}

export enum ContentStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED'
}

export enum NotificationType {
  GENERAL = 'GENERAL',
  BATCH = 'BATCH',
  PERSONAL = 'PERSONAL',
  TRAINING = 'TRAINING',
  RECRUITMENT = 'RECRUITMENT',
  RESULT = 'RESULT',
  SYSTEM = 'SYSTEM'
}
